version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro # monta script para criar bancos

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  clients-service:
    build:
      context: .
      dockerfile: apps/clients/Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/clients_db
      REDIS_URL: redis://redis:6379

  transactions-service:
    build:
      context: .
      dockerfile: apps/transactions/Dockerfile
    ports:
      - '3002:3002'
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 3002
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/transactions_db
      REDIS_URL: redis://redis:6379

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - clients-service
      - transactions-service
    environment:
      PORT: 3000
      # Gateway pode ou não usar banco, se usar, ajustar a URL, caso contrário remova
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/clients_db
      REDIS_URL: redis://redis:6379

volumes:
  pgdata:
